FROM apacheignite/ignite:2.6.0

ADD shared-model-1.5-SNAPSHOT.jar ${IGNITE_HOME}/libs
ADD log4j.xml ${IGNITE_HOME}
ADD gson-2.8.2.jar ${IGNITE_HOME}/libs 
ADD joda-time-2.9.9.jar ${IGNITE_HOME}/libs
ADD commons-lang3-3.8.jar ${IGNITE_HOME}/libs